### ISSUE TITLE
How do i install it

### ISSUE THREAD

**Issue by FrostNovaHD** [vixalien/force-phone-mode#1]

**Comment by vixalien** [comment]
You are supposed to clone this repo and put it into `~/.local/share/gnome-shell/extensions/force-phone-mode@vixalien.com`.

Here is a painfully simple one-liner:

```sh
git clone https://github.com/vixalien/force-phone-mode.git ~/.local/share/gnome-shell/extensions/force-phone-mode@vixalien.com
```

If the one-liner works, you can let me know so I can put it in the README

**Comment by FrostNovaHD** [comment]
> You are supposed to clone this repo and put it into `~/.local/share/gnome-shell/extensions/force-phone-mode@vixalien.com`.
> 
> Here is a painfully simple one-liner:
> 
> ```shell
> git clone https://github.com/vixalien/force-phone-mode.git ~/.local/share/gnome-shell/extensions/force-phone-mode@vixalien.com
> ```
> 
> If the one-liner works, you can let me know so I can put it in the README

It works
