### ISSUE TITLE
Not working with gnome-shell-mobile 46-mobile.1 on nixos

### ISSUE THREAD

**Issue by maritain48** [vixalien/force-phone-mode#2]
Thanks for creating this helpful extension! I'm able to install this extension and enable it on a vanilla nixos installation in a vm running gnome-shell-mobile [46-mobile.1](https://gitlab.gnome.org/verdre/gnome-shell-mobile/-/tree/46-mobile.1) through nixpkgs overlay [nixpkgs-gnome-mobile](https://github.com/chuangzhu/nixpkgs-gnome-mobile), but it doesn't have any effect. Is it working for anyone currently?

**Comment by vixalien** [comment]
To be honest, I don't use this extension anymore, but it should work. Are you sure it's installed and enabled?

**Comment by maritain48** [comment]
Thanks for the answer. Yes I'm sure it is enabled. I also didn't have success finding the cause through checking different gnome related logs. May I ask you know of another way of forcing phone mode or you just don't need this functionality anymore?

**Comment by vixalien** [comment]
You can access the Looking Glass by typing <kbd>Alt</kbd>+<kbd>F2</kbd> then `lg` and type the following, and then it should turn on the phone mode, at least until you logout.

```js
// run this line first, and wait for it to complete
import("resource:///org/gnome/shell/ui/main.js").then(module => globalThis.Main = module);


// then run these second
const oldCheckIsPhone = Main.layoutManager._checkIsPhone;
Main.layoutManager._checkIsPhone = () => true;
Main.layoutManager._updateIsPhone();
```

Report back if it works

**Comment by maritain48** [comment]
@vixalien thanks running the code you posted works! The code in the plugin is the same?

**Comment by vixalien** [comment]
Yeah the code in the extension is the same. Did you try enabling the
extension and then logging out?

**Comment by maritain48** [comment]
Okay. Yes I tried logging out and in again after enabling the extension.

**Comment by maritain48** [comment]
No problem. Thanks for the hints about looking glass and executing the code directly. This makes it more easy for me to continue debugging.

**Comment by maritain48** [comment]
So I found the problem. It is because I use gnome-shell-mobile version `46-mobile.1` which for now is not supported in the [extension](https://github.com/vixalien/force-phone-mode/blob/09a5b6e7613a2951b89c3dd305a9094f873f2713/) . Adding this version in metadata.json under shell-version makes this extension work.

**Comment by vixalien** [comment]
Sure, PRs are appreciated

**Comment by maritain48** [comment]
To address this issue I created #3. Can you please check it out?

**Comment by maritain48** [comment]
Sorry I forgot a comma: https://github.com/vixalien/force-phone-mode/pull/4 Should have tested my pr code... Sorry!
